config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
   root to: 'notes#index'
    resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    load_notes
  end

  def new
    build_note
  end

  def show
    load_note
  end

  def create
    build_note
    save_note or render 'new'
  end

  def edit
    load_note
    build_note
  end

  def update
    load_note
    build_note
    save_note or render 'edit'
  end

  def destroy
    load_note
    @note.destroy 
    redirect_to notes_path
  end

  private
  
  def load_notes
    @notes ||= note_scope.to_a
  end
  
  def load_note
    @note ||= note_scope.find(params[:id])
  end

  def build_note
    @note ||= note_scope.build
    @note.attributes = note_params
  end

  def save_note
    if @note.save
       redirect_to @note
    end
  end

  def note_params
    note_params = params[:note]
    note_params ? note_params.permit(:title, :text, :published) : {}
  end

  def note_scope
    Note.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
      our_input_text = " Hello from Rails and the follow is "
      @heart = `python lib/assets/python/heart.py "#{our_input_text}"`
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CleanCode</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note, local: true) do |form| %>
    <% if note.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@note.errors.count, "error") %>
            prohibited this note from being saved:</h2>

            <ul>
                <% note.errors.full_messages.each do |message| %>
                    <li><%= message %>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :title %>
        <%= form.text_field :text %><br>
        
        <%= form.label :text %>
        <%= form.text_area:text %><br>

        <%= form.label :published %>
        <%= form.date_field :published %><br>


        <%#= from.date_field :plublished %>
    </div>

    <div class="actions">
        <%= form.submit %>
    </div>
    <% end %>

app/views/notes/edit.html.erb
<h1>Editing Company </h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1> Notes </h1>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th colspan="3"></th>
        </tr>
    </thead>
      <tbody>
        <% @notes.each do |note| %>
         <tr>
             <td><%= note.title %></td>
             <td><%= note.text %></td>
             <td><%= note.published %></td>
             <td><%= link_to "Show", note %></td>
             <td><%= link_to "Edit", edit_note_path(note) %></td>
             <td><%= link_to "Destroy", note, method: :delete,
                 data: { confirm: 'are you sure?' }%></td>
         </tr>
      <% end %>
      </tbody>
</table>
<br>


<%= link_to 'new note', new_note_path %>

app/views/notes/new.html.erb
<h1>New NOte</h1>

<%= render 'form', note: @note %>
<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<P id="notice"><%= notice %>

<p>
<strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
<strong>Text:</strong>
  <%= @note.text%>
</p>

<p>
<strong>Published:</strong>
  <%= @note.published %>
</p>

<%= link_to "edit", edit_note_path(@note) %> |
<%= link_to "back", notes_path %>

app/views/pages/home.html.erb
<h1>Home</h1>
<p>Code From rails fist and then python <%= @heart %></p>